package com.se.dao.pojo;

// default package
// Generated 2019-1-9 14:21:15 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SysRole generated by hbm2java
 */
@Entity
@Table(name = "sys_role", catalog = "tgyj")
public class SysRole implements java.io.Serializable {

	private int rid;
	private String rname;
	private String rbianma;
	private int oid;
    private String ruser;





	public SysRole() {
	}

	public SysRole(int rid, String rname, String rbianma, int oid,String ruser) {
		this.rid = rid;
		this.rname = rname;
		this.rbianma = rbianma;
		this.oid = oid;
		this.ruser=ruser;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "rid", unique = true, nullable = false)
	public int getRid() {
		return this.rid;
	}

	public void setRid(int rid) {
		this.rid = rid;
	}

	@Column(name = "rname", nullable = false)
	public String getRname() {
		return this.rname;
	}

	public void setRname(String rname) {
		this.rname = rname;
	}

	@Column(name = "rbianma", nullable = false)
	public String getRbianma() {
		return this.rbianma;
	}

	public void setRbianma(String rbianma) {
		this.rbianma = rbianma;
	}

	@Column(name = "oid")
	public int getOid() {
		return this.oid;
	}

	public void setOid(int oid) {
		this.oid = oid;
	}

    @Column(name = "ruser")
    public String getRuser() {
        return ruser;
    }

    public void setRuser(String ruser) {
        this.ruser = ruser;
    }

}
