package com.se.dao.pojo;


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import com.fasterxml.jackson.annotation.JsonFormat;

/**
 * SysUser generated by hbm2java
 */
@Entity
@Table(name = "sys_user", catalog = "tgyj")
public class SysUser implements java.io.Serializable {

	private int uid;
	private String username;
	private String password;
	private String email;
	private String phone;
	private String registerAddress;
	private Date registerTime;
	@JsonFormat(pattern = "yyyy/MM/DD")
	private Date loginTime;
	@JsonFormat(pattern = "yyyy/MM/DD")
	private Date lastLoginTime;
	private String loginCount;
	private String signed;
	private Integer roleid;
	private Integer organizeid;
	private Integer opid;
	
	/* private String rname; */

	public SysUser() {
	}

	public SysUser(int uid, String username, String password, String email, String phone) {
		this.uid = uid;
		this.username = username;
		this.password = password;
		this.email = email;
		this.phone = phone;
	}

	public SysUser(int uid, String username, String password, String email, String phone, String registerAddress,
			Date registerTime, Date loginTime, Date lastLoginTime, String loginCount, String signed, Integer roleid,
			Integer organizeid, Integer opid) {
		this.uid = uid;
		this.username = username;
		this.password = password;
		this.email = email;
		this.phone = phone;
		this.registerAddress = registerAddress;
		this.registerTime = registerTime;
		this.loginTime = loginTime;
		this.lastLoginTime = lastLoginTime;
		this.loginCount = loginCount;
		this.signed = signed;
		this.roleid = roleid;
		this.organizeid = organizeid;
		this.opid = opid;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "uid", unique = true, nullable = false)
	
	public int getUid() {
		return this.uid;
	}

	public void setUid(int uid) {
		this.uid = uid;
	}

	@Column(name = "username", nullable = false)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", nullable = false)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "email", nullable = false)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "phone", nullable = false)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "register_address")
	public String getRegisterAddress() {
		return this.registerAddress;
	}

	public void setRegisterAddress(String registerAddress) {
		this.registerAddress = registerAddress;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "register_time", length = 19)
	public Date getRegisterTime() {
		return this.registerTime;
	}

	public void setRegisterTime(Date registerTime) {
		this.registerTime = registerTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "login_time", length = 19)
	public Date getLoginTime() {
		return this.loginTime;
	}

	public void setLoginTime(Date loginTime) {
		this.loginTime = loginTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_login_time", length = 19)
	public Date getLastLoginTime() {
		return this.lastLoginTime;
	}

	public void setLastLoginTime(Date lastLoginTime) {
		this.lastLoginTime = lastLoginTime;
	}

	@Column(name = "login_count")
	public String getLoginCount() {
		return this.loginCount;
	}

	public void setLoginCount(String loginCount) {
		this.loginCount = loginCount;
	}

	@Column(name = "signed")
	public String getSigned() {
		return this.signed;
	}

	public void setSigned(String signed) {
		this.signed = signed;
	}

	@Column(name = "roleid")
	public Integer getRoleid() {
		return this.roleid;
	}

	public void setRoleid(Integer roleid) {
		this.roleid = roleid;
	}

	@Column(name = "organizeid")
	public Integer getOrganizeid() {
		return this.organizeid;
	}

	public void setOrganizeid(Integer organizeid) {
		this.organizeid = organizeid;
	}

	@Column(name = "opid")
	public Integer getOpid() {
		return opid;
	}

	public void setOpid(Integer opid) {
		this.opid = opid;
	}
	/*
	 * @Transient public String getRname() { return rname; }
	 * 
	 * public void setRname(String rname) { this.rname = rname; }
	 */
	

	

}
